#!/usr/bin/env python
"""Regenerate the committed 50/450 split and the 8-question smoke list.

Reads the pinned LongMemEval-S file (fetch it first with
scripts/fetch_longmemeval.py), verifies its sha256 against the pin, then
writes deterministic artifacts (issue #7):

- eval/datasets/splits/longmemeval_s_cleaned/split.json  — 50/450 ids,
  seed, algorithm and per-stratum counts (question_type x abstention);
- eval/datasets/splits/longmemeval_s_cleaned/smoke.json  — the fixed
  8-question smoke subset (six question types + two abstention ids,
  drawn from the development side only);
- eval/configs/examples/real_smoke_offline.toml — the offline smoke
  config over those 8 real ids (fake memory/reader/judge, no network).

Rerunning against the same pinned data reproduces the artifacts
byte-identically (no timestamps inside the artifacts).

Usage:
    uv run python scripts/make_split.py           # write artifacts
    uv run python scripts/make_split.py --check    # verify committed files
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from eval.contracts.common import ContractError
from eval.datasets.longmemeval import (
    DATASET_PLAN,
    DEFAULT_LONGMEMEVAL_S_PATH,
    FILE_SHA256,
    LongMemEvalDataset,
)
from eval.datasets.split import (
    SMOKE_SEED,
    SPLIT_DIR_NAME,
    SPLIT_SEED,
    SmokePlan,
    SplitPlan,
    select_smoke,
    stratified_split,
)
from scripts.fetch_longmemeval import sha256_file

REPO_ROOT = Path(__file__).resolve().parents[1]
SPLIT_DIR = (
    REPO_ROOT / "eval" / "datasets" / "splits" / SPLIT_DIR_NAME
)
CONFIG_PATH = REPO_ROOT / "eval" / "configs" / "examples" / "real_smoke_offline.toml"

#: Development/holdout sizes fixed by the design (数据与划分).
DEV_SIZE = 50

CONFIG_TEMPLATE = """# M2 real-data offline smoke config (generated by scripts/make_split.py;
# smoke semantics aligned with the M1 offline_fake subset: six question
# types + two abstention ids, drawn from the DEV side of the 50/450 split).
# Requires the pinned LongMemEval-S file: run scripts/fetch_longmemeval.py
# first. Fake memory/reader/judge only — no external model is contacted.

name = "real-smoke-offline"
dataset_plan = "longmemeval-s-cleaned@1"
sample_plan_id = "longmemeval-s-smoke-8"
sample_ids = [
{sample_id_lines}
]
smoke_subset_ids = [
{sample_id_lines}
]
evidence_token_budget = 4096
notes = "8 real LongMemEval-S questions through the full offline loop with fake components; smoke scores never enter formal reports."

[memory]
name = "fake-memory"
baseline_kind = "adapter"
capabilities = [
  "extractive_evidence",
  "generated_evidence",
  "state_inspection",
  "async_mutation",
  "idempotent_mutation",
  "operation_status",
]

[memory.config]
mutation_mode = "async"
evidence_kinds = ["extractive", "generated"]
retrieval_mode = "match"
idempotent = true
state_inspection = true
async_lag = 1

[reader]
model = "fake-reader"
model_family = "fake-reader-family"
base_url = "offline://fake"
temperature = 0.0
max_output_tokens = 1024
tokenizer_id = "test:char-v1"
counting_mode = "test"

[judge]
model = "fake-judge"
model_family = "fake-judge-family"
base_url = "offline://fake"
temperature = 0.0
protocol_id = "longmemeval-yes-no@1"
protocol_source_commit = "0000000000000000000000000000000000000000"

[run_params]
max_retries = 3
backoff_base_s = 1.0
await_ready_timeout_s = 300.0
question_concurrency = 1
"""


def build_plans(data_path: Path) -> tuple[SplitPlan, SmokePlan]:
    """Pure generation from the pinned file (no writes)."""
    if not data_path.exists():
        raise ContractError(
            code="dataset_missing",
            message=(
                f"{data_path} not found; run "
                "`uv run python scripts/fetch_longmemeval.py` first"
            ),
            location=str(data_path),
        )
    actual = sha256_file(data_path)
    if actual != FILE_SHA256:
        raise ContractError(
            code="dataset_pin_mismatch",
            message=(
                f"{data_path} hashes to {actual} but the pin expects "
                f"{FILE_SHA256}; the split must come from the pinned revision"
            ),
            location=str(data_path),
        )
    dataset = LongMemEvalDataset.from_file(data_path)
    items = dataset.iter_split_items()
    split = stratified_split(
        items,
        dev_size=DEV_SIZE,
        seed=SPLIT_SEED,
        dataset_plan=DATASET_PLAN,
        source_sha256=actual,
    )
    smoke = select_smoke(
        items,
        seed=SMOKE_SEED,
        dataset_plan=DATASET_PLAN,
        source_sha256=actual,
        split=split,
    )
    return split, smoke


def _render(split: SplitPlan, smoke: SmokePlan) -> dict[str, str]:
    ids = ",\n".join(f'  "{h}"' for h in smoke.smoke_ids)
    return {
        "split.json": split.model_dump_json(indent=2) + "\n",
        "smoke.json": smoke.model_dump_json(indent=2) + "\n",
        str(CONFIG_PATH.name): CONFIG_TEMPLATE.format(sample_id_lines=ids),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="make_split",
        description=(
            "Regenerate the committed 50/450 split + smoke artifacts from "
            "the pinned LongMemEval-S file"
        ),
    )
    parser.add_argument(
        "--data",
        default=None,
        metavar="PATH",
        help=f"data file (default: {DEFAULT_LONGMEMEVAL_S_PATH})",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare against the committed artifacts without writing",
    )
    args = parser.parse_args(argv)
    try:
        split, smoke = build_plans(Path(args.data or DEFAULT_LONGMEMEVAL_S_PATH))
    except ContractError as exc:
        print(
            f"error: {exc.code} at {exc.location or '(root)'}: {exc.message}",
            file=sys.stderr,
        )
        return 2

    files = _render(split, smoke)
    targets = {
        "split.json": SPLIT_DIR / "split.json",
        "smoke.json": SPLIT_DIR / "smoke.json",
        str(CONFIG_PATH.name): CONFIG_PATH,
    }
    if args.check:
        stale = [
            name
            for name, path in targets.items()
            if not path.exists() or path.read_text(encoding="utf-8") != files[name]
        ]
        if stale:
            print(
                f"error: committed artifacts differ from regeneration: {stale}",
                file=sys.stderr,
            )
            return 1
        print("committed split/smoke artifacts match regeneration")
        return 0

    SPLIT_DIR.mkdir(parents=True, exist_ok=True)
    for name, path in targets.items():
        path.write_text(files[name], encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    abs_dev = sum(s.dev for k, s in split.strata.items() if k.endswith("|abs"))
    print(
        json.dumps(
            {
                "dev": len(split.dev_ids),
                "holdout": len(split.holdout_ids),
                "dev_abstention": abs_dev,
                "holdout_abstention": 30 - abs_dev,
                "smoke_ids": list(smoke.smoke_ids),
            },
            indent=2,
            ensure_ascii=False,
        )
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
